export const DECISION_TYPES = {
  AUTO_CONTESTED: {
    key: "AUTO_CONTESTED",
    label: "AUTO_CONTESTED",
    shortLabel: "Contested",
    description: "Strong physical telemetry; legal representment uploaded to NPCI/Razorpay",
    badgeClass: "bg-emerald-50 text-emerald-700 border border-emerald-200/90 font-medium",
    dotClass: "bg-emerald-600",
    color: "#059669",
  },
  NEEDS_REVIEW: {
    key: "NEEDS_REVIEW",
    label: "NEEDS_REVIEW",
    shortLabel: "Needs Review",
    description: "Ambiguous telemetry signals; awaiting risk officer manual verdict",
    badgeClass: "bg-amber-50 text-amber-700 border border-amber-200/90 font-medium",
    dotClass: "bg-amber-500",
    color: "#d97706",
  },
  AUTO_ACCEPTED: {
    key: "AUTO_ACCEPTED",
    label: "AUTO_ACCEPTED",
    shortLabel: "Liability Released",
    description: "Zero-liability release; ₹1,500 bank penalty successfully avoided",
    badgeClass: "bg-rose-50 text-rose-700 border border-rose-200/90 font-medium",
    dotClass: "bg-rose-600",
    color: "#e11d48",
  },
  PENDING: {
    key: "PENDING",
    label: "PENDING",
    shortLabel: "Auditing",
    description: "Dispute received; awaiting queue worker telemetry extraction",
    badgeClass: "bg-slate-100 text-slate-600 border border-slate-200 font-medium",
    dotClass: "bg-slate-400 animate-pulse",
    color: "#64748b",
  },
};

export const BANK_LOSS_PENALTY_INR = 1500;

export const SCENARIOS = [
  {
    id: "winnable_clean",
    title: "1. Clean Winnable Chargeback",
    subtitle: "High Telemetry • Doorstep OTP • GPS 42m",
    description: "Customer claimed 'Product Not Received', but carrier recorded valid 4-digit doorstep OTP, 42m geofence accuracy, matching weight scale, and clean POD.",
    expectedDecision: "AUTO_CONTESTED",
    expectedScore: 95,
    tagColor: "emerald",
    riskSignal: "High merchant confidence (+95 pts)",
    financialOutcome: "Dispute contested automatically via NPCI UDIR packet",
  },
  {
    id: "customer_defect_ticket",
    title: "2. Pre-Dispute Support Ticket",
    subtitle: "Fairness Gate Triggered • Early Release",
    description: "Telemetry is technically clean (+85 pts), but ChromaDB RAG detects the buyer opened Zendesk Ticket #4910 reporting transit damage 2 days prior to filing the chargeback.",
    expectedDecision: "AUTO_ACCEPTED",
    expectedScore: 85,
    tagColor: "rose",
    riskSignal: "Consumer Fairness Gate tripped (Support Defect Ticket)",
    financialOutcome: "Released early to avoid guaranteed ₹1,500 bank penalty",
  },
  {
    id: "transit_weight_loss",
    title: "3. Transit Weight Loss (> 100g)",
    subtitle: "Carrier Tampering • 280g Missing",
    description: "Hub scale measured 1,450g; doorstep delivery scale registered 1,170g (delta: -280g / 19.3%). Indicates transit pilferage or damaged box before doorstep arrival.",
    expectedDecision: "AUTO_ACCEPTED",
    expectedScore: 45,
    tagColor: "rose",
    riskSignal: "Consumer Fairness Gate tripped (Weight loss > 100g)",
    financialOutcome: "Merchant protected from ₹1,500 loss fee",
  },
  {
    id: "obd_clean",
    title: "4. Open Box Delivery (OBD) Verified",
    subtitle: "Doorstep Unboxing • Tamper Seal Logged",
    description: "High-value electronics parcel delivered under Open Box protocol. Courier logged intact internal serial number, customer verified item physically at doorstep.",
    expectedDecision: "AUTO_CONTESTED",
    expectedScore: 98,
    tagColor: "emerald",
    riskSignal: "Deterministic OBD Checklist (+98 pts)",
    financialOutcome: "Bulletproof NPCI legal defense packet compiled",
  },
  {
    id: "fraud_no_otp",
    title: "5. Failed OTP & Rogue Geofence",
    subtitle: "No OTP • 1.8km Geofence Drift",
    description: "Delivery recorded without customer OTP. Driver coordinate was 1,840m away from shipping address, and signature is illegible. Driver likely misdelivered or dumped package.",
    expectedDecision: "AUTO_ACCEPTED",
    expectedScore: 18,
    tagColor: "rose",
    riskSignal: "Critical telemetry failure (18 pts)",
    financialOutcome: "Zero-liability release avoids card network penalty",
  },
];
